name: criteo-release

on: release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout security kibana
      uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
      
    - name: Test and Build
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
        export NVM_HOME="$HOME/.nvm"
        ./build.sh
        artifact_path=`ls $(pwd)/target/releases/opendistro_security_kibana_plugin-*.zip`
        artifact_name=`basename $artifact_path`
        echo ::set-env name=ARTIFACT_PATH::$artifact_path
        echo ::set-env name=ARTIFACT_NAME::$artifact_name
        echo ::set-env name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Upload
      uses: fnkr/github-action-ghr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GHR_PATH: target/releases/

